// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartLoad.Infrastructure.Persistence;

#nullable disable

namespace SmartLoad.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartLoad.Domain.Entities.LoadPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PackedItems")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("UnpackedItems")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("LoadPlans", (string)null);
                });

            modelBuilder.Entity("SmartLoad.Domain.Entities.LoadPlan", b =>
                {
                    b.OwnsOne("SmartLoad.Domain.Entities.Vehicle", "Vehicle", b1 =>
                        {
                            b1.Property<Guid>("LoadPlanId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<double>("MaxPayload")
                                .HasColumnType("double precision");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("VehicleName");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("LoadPlanId");

                            b1.ToTable("LoadPlans");

                            b1.WithOwner()
                                .HasForeignKey("LoadPlanId");

                            b1.OwnsOne("SmartLoad.Domain.Common.Dimensions", "InnerDimensions", b2 =>
                                {
                                    b2.Property<Guid>("VehicleLoadPlanId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Depth")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Height")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Width")
                                        .HasColumnType("double precision");

                                    b2.HasKey("VehicleLoadPlanId");

                                    b2.ToTable("LoadPlans");

                                    b2.WithOwner()
                                        .HasForeignKey("VehicleLoadPlanId");
                                });

                            b1.Navigation("InnerDimensions")
                                .IsRequired();
                        });

                    b.Navigation("Vehicle")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
